language: android

env:
  global:
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ANDROID_COMPILE_SDK_VERSION=25
    - ANDROID_EMULATOR_API_LEVEL=19
    - ANDROID_ABI=armeabi-v7a

before_install:
 - chmod +x ./gradlew
 - mkdir "$ANDROID_HOME/licenses" || true
 - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"          # Accept ConstraintLayout licenses
 - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

 # Emulator Management: create, start and wait
 - echo no | android create avd --force -n test -t android-$ANDROID_EMULATOR_API_LEVEL --abi $ANDROID_ABI
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &

jdk:
  - oraclejdk8

android:
    components:
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    # The SDK version used to compile your project
    - android-$ANDROID_COMPILE_SDK_VERSION

    - android-$ANDROID_EMULATOR_API_LEVEL
    
    # design support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # Additional components
    
    # System image for emulator during tests
    - sys-img-$ANDROID_ABI-android-$ANDROID_EMULATOR_API_LEVEL
