language: android
android:
    components:
    # The BuildTools version used by your project
    - build-tools-25.0.2
    
    # The SDK version used to compile your project
    - android-25
    
    
    # Additional components
    
    # System image for emulator during tests
    - sys-img-armeabi-v7a-android-22