language: android

before_install:
 - chmod +x ./gradlew
 - mkdir "$ANDROID_HOME/licenses" || true
 - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"          # Accept ConstraintLayout licenses
 - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

jdk:
  - oraclejdk8

android:
    components:
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-25.0.2
    
    # The SDK version used to compile your project
    - android-25
    
    # design support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    
    # Additional components
    
    # System image for emulator during tests
    - sys-img-x86-android-23
